const products = window.PERFUME_PRODUCTS || [];
const suppliers = [
  ['Mister Smell','от 5 000 ₽','Ниша + оригинальные тестеры, от 1 флакона','Договор и закрывающие документы','№1','https://mistersmell.ru/optom/'],
  ['Pure Perfume','от 10 000 ₽','Нишевая и luxury парфюмерия, тестеры','Прайс через менеджера, 100% предоплата','№2','https://pureperfume.ru/testers/'],
  ['PrimeParfum','от 15 000 ₽','Оригинал, тестеры, некондиция, параллельный импорт','ИП/юрлица, УПД/ТТН, маркировка','№3','https://www.primeparfum.ru/'],
  ['Galara','от 25 000 ₽','Селектив, тестеры, отливанты','Договор и пакет документов','№4','https://galara.ru/'],
  ['AromaOpt','ориентир от 60 000 ₽','Большой селективный ассортимент','Полный комплект документов','№5','https://www.aromaopt.ru/?mode=pricelist'],
  ['Kosmetik-stor Opt','по запросу','Тестеры, миниатюры, отливанты','Оригинал, маркировка','№6','https://opt.kosmetik-stor.ru/'],
  ['ПарфюмОптом Компани','от 1 шт.','20 000+ позиций, отливанты','Требуется усиленная проверка перед крупной оплатой','№7','https://parfumoptom-company.ru/'],
  ['OptList','зависит от поставщика','Агрегатор для массового тендера','Проверять каждого поставщика отдельно','Доп.','https://optlist.ru/wholesales/parfium']
];
const quotes = {'Tiziana Terenzi|Kirke|Mister Smell':{price:9336,format:'Tester original, 100 ml'}};
const requestText = `Добрый день!\n\nЗапускаем проект по продаже оригинальной нишевой парфюмерии в распив.\nПросим дать оптовое предложение по приложенной матрице.\n\nПо каждой позиции нужны:\n1. Наличие.\n2. Формат: retail / tester / refill / некондиция / другой.\n3. Объем.\n4. Цена за 1 шт.\n5. Возможность покупки от 1 флакона.\n6. Маркировка / Data Matrix.\n7. Какие документы предоставляете: УПД, декларации, договор.\n8. Срок отгрузки.\n\nПри наличии нескольких форматов одного аромата просим дать все варианты — для нас важна минимальная стоимость оригинальной жидкости, упаковка флакона вторична.\n\nПлан первой закупки — до 400 000 ₽. После теста спроса предполагаем регулярные закупки.`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=s=>Number(String(s).replace(/[^0-9]/g,''))||0;
const rub=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function fallbackHTML(p){return `<div class="fallback"><div class="fallback-stage" aria-hidden="true"><div class="fallback-cap"></div><div class="fallback-bottle"><div class="fallback-label"><span>${esc(p.brand)}</span><strong>${esc(p.name)}</strong></div></div></div><div class="fallback-caption"><b>${esc(p.brand)}</b><span>${esc(p.name)}</span><em>визуализация товара</em></div></div>`;}
function renderMetrics(){const bottles=products.reduce((a,p)=>a+num(p.tags[1]),0);const budget=products.reduce((a,p)=>a+num(p.max_buy)*num(p.tags[1]),0);const revenue=products.reduce((a,p)=>a+(num(p.tags[0])/5)*num(p.p5)*num(p.tags[1]),0);document.getElementById('metrics').innerHTML=[[products.length+' SKU','первая физическая матрица'],[bottles+' флаконов','с учетом дублей хитов'],[rub(budget),'максимальный товарный бюджет'],[rub(revenue),'теоретическая выручка при продаже по 5 мл*']].map(x=>`<div class="metric"><strong>${esc(x[0])}</strong><span>${esc(x[1])}</span></div>`).join('');}
function renderCatalog(){const el=document.getElementById('catalogGrid');el.innerHTML=products.map((p,i)=>`<article class="product-card" data-role="${esc(p.role)}" data-search="${esc(p.search)}"><div class="product-image"><span class="num">${String(i+1).padStart(2,'0')}</span><span class="status ${esc(p.state)}">${esc(p.status)}</span><img src="${esc(p.image)}" alt="${esc(p.brand+' '+p.name)}" loading="lazy">${fallbackHTML(p)}</div><div class="product-body"><div class="brand">${esc(p.brand)}</div><h3>${esc(p.name)}</h3><div class="tags">${p.tags.map(t=>`<span>${esc(t)}</span>`).join('')}</div><div class="buy-grid"><div><small>MAX закупка</small><strong>${esc(p.max_buy)}</strong></div><div><small>Публичный ориентир</small><strong>${esc(p.market)}</strong><em>${esc(p.market_note)}</em></div></div><div class="retail-title">Наша розница</div><div class="retail-grid"><div><span>2 мл</span><b>${esc(p.p2)}</b></div><div class="accent"><span>5 мл</span><b>${esc(p.p5)}</b></div><div><span>10 мл</span><b>${esc(p.p10)}</b></div></div><p>${esc(p.note)}</p><a href="${esc(p.source)}" target="_blank" rel="noopener">Источник / ориентир ↗</a></div></article>`).join('');el.querySelectorAll('img').forEach(img=>img.addEventListener('error',()=>{img.style.display='none';if(img.nextElementSibling)img.nextElementSibling.style.display='flex';}));}
function renderTender(){const mainSuppliers=suppliers.slice(0,7);const headers=mainSuppliers.map(s=>`<th>${esc(s[0])}</th>`).join('');const rows=products.map(p=>{const max=num(p.max_buy),vol=num(p.tags[0]),qty=num(p.tags[1]);let best=null;const cells=mainSuppliers.map(s=>{const q=quotes[p.brand+'|'+p.name+'|'+s[0]];if(!q)return '<td class="quote empty">запрос</td>';if(!best||q.price<best.price)best={...q,supplier:s[0]};const cls=q.price<=max?'pass':'fail';return `<td class="quote ${cls}"><strong>${rub(q.price)}</strong><small>${esc(q.format)}</small></td>`;}).join('');const decision=!best?['wait','НУЖЕН ПРАЙС']:best.price<=max?['pass','ЗАКУПАЕМ']:['fail','ИЩЕМ ДЕШЕВЛЕ'];const winner=best?`<strong>${esc(best.supplier)}</strong><small>${rub(best.price)}</small>`:'—';return `<tr><td class="sticky"><strong>${esc(p.brand)}</strong><span>${esc(p.name)}</span></td><td>${vol} мл</td><td>${qty}</td><td><strong>${rub(max)}</strong></td>${cells}<td class="${decision[0]}">${winner}</td><td><span class="decision ${decision[0]}">${decision[1]}</span></td></tr>`;}).join('');document.getElementById('tenderBox').innerHTML=`<table><thead><tr><th>Товар</th><th>Объем</th><th>Кол.</th><th>MAX закупка</th>${headers}<th>Победитель</th><th>Решение</th></tr></thead><tbody>${rows}</tbody></table>`;}
function renderSuppliers(){document.getElementById('supplierBox').innerHTML=`<table><thead><tr><th>Поставщик</th><th>Мин. заказ</th><th>Что ищем</th><th>Документы / схема</th><th>Ссылка</th></tr></thead><tbody>${suppliers.map(s=>`<tr><td><strong>${esc(s[0])}</strong><div class="priority">${esc(s[4])}</div></td><td>${esc(s[1])}</td><td>${esc(s[2])}</td><td>${esc(s[3])}</td><td><a href="${esc(s[5])}" rel="noopener" target="_blank">Открыть ↗</a></td></tr>`).join('')}</tbody></table>`;}
function init(){renderMetrics();renderCatalog();renderTender();renderSuppliers();document.getElementById('requestText').textContent=requestText;let activeRole='all';const apply=()=>{const q=(document.getElementById('search').value||'').toLowerCase().trim();document.querySelectorAll('.product-card').forEach(c=>c.classList.toggle('hide',!((activeRole==='all'||c.dataset.role===activeRole)&&(!q||(c.dataset.search||'').includes(q)))));};document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{activeRole=b.dataset.filter;apply();}));document.getElementById('search').addEventListener('input',apply);document.getElementById('copyBtn').addEventListener('click',async()=>{const btn=document.getElementById('copyBtn');try{await navigator.clipboard.writeText(requestText);const old=btn.innerText;btn.innerText='Скопировано';setTimeout(()=>btn.innerText=old,1200);}catch(e){btn.innerText='Скопируйте текст вручную';}});}
init();